### ISSUE TITLE
How can we simulate radial/transversal(R/T) or north/east (N/E) component ambient noise recording? 

### ISSUE THREAD

**Issue by xichaoqiang** [ekaestle/amb_noise_tools#3]
Hello,

I am very interested in three component ambient noise recording simluation.

How can I simulate three component ambient noise recording with your scritpts?

Thank you very much.

Best regards,
Xi

**Comment by ekaestle** [comment]
Dear Xi,
thanks for your interest in my ambient noise package!
Unfortunately, the scripts are not really suitable to simulate full 3-component ambient noise records. In the scripts, you will only find a simple forward calculator that uses the 2D Green's function for a homogeneous, lossless medium (based on Appendix E of Boschi and Weemstra, 2015, "Stationary-phase integrals in the cross correlation of ambient noise"). 
If you want to simulate the 3D noise field in a layered, heterogeneous medium, you will probably have to use something like SPECFM3D, so that you can obtain synthetic Love- and Rayleigh waves.
Best regards,
Emanuel

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
